[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.italic]
family = "JetBrainsMono Nerd Font"

[env]
TERM = "xterm-256color"

[window]
decorations = "full"
decorations_theme_variant = "Dark"
opacity = 1.0

[window.dimensions]
columns = 120
lines = 30

[colors.primary]
background = "#1e1e1e"     # macOS dark gray
foreground = "#CDD6F4"     # WhiteSur light text

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[colors.search.matches]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[colors.normal]
black   = "0x0d0d0d"
red     = "#ff453a"
green   = "#32d74b"
yellow  = "#ffd60a"
blue    = "#0a84ff"
magenta = "#bf5af2"
cyan    = "#5ac8fa"
white   = "#f2f2f7"

[colors.bright]
black   = "#3a3a3c"
red     = "#ff6961"
green   = "#63e6a0"
yellow  = "#ffe168"
blue    = "#4facff"
magenta = "#d28cff"
cyan    = "#89e2ff"
white   = "#ffffff"
